name: mcgreen-acres
recipe: drupal8
config:
  webroot: web
  xdebug: true
  php: "7.0"
  composer_version: 1
tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/web --uri=http://mcgreen-acres.lndo.site"
