name: mcgreen-acres
recipe: drupal11
config:
  database: mariadb:11.4
  webroot: web
  xdebug: true
  php: "8.4"
  composer_version: 2
services:
  mail:
    type: mailpit
    mailFrom:
      - appserver
proxy:
  mail:
    - mail-mcgreen-acres.lndo.site
tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/web --uri=http://mcgreen-acres.lndo.site"
  build:
    service: appserver
    cmd:
      - composer install
      - /app/vendor/bin/drush sql-drop -y
      - /app/vendor/bin/drush sql-sync @prod @self -y
      - /app/vendor/fourkitchens/pots/scripts/general/remote/drush-commands "" "/app/vendor/bin/drush --root=/app/web --uri=http://mcgreen-acres.lndo.site" "YES"
