<?php

/**
 * @file
 * Password Reset Landing Page Password policy submodule.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_help().
 */
function prlp_password_policy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.prlp_password_policy':
      $output = '';
      $output .= '<p>' . t('Provides integration between the Password Reset Landing Page and Password Policy modules.') . '</p>';
      $output .= '<p>' . t('Ideas and code borrowed from <a href=":url" target="_blank">password policy extras</a> module.', [':url' => 'https://www.drupal.org/project/password_policy_extras']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for user_pass_reset().
 */
function prlp_password_policy_form_user_pass_reset_alter(&$form, FormStateInterface $form_state) {
  $uid = \Drupal::routeMatch()->getParameter('uid');
  $user = User::load($uid);
  if ($user && \Drupal::service('prlp_password_policy.validation_manager')->tableShouldBeVisible()) {

    $form['#attached']['library'][] = 'prlp_password_policy/prlp_password_policy';

    $constraints = \Drupal::service('password_policy.validator')
      ->buildPasswordPolicyConstraintsTableRows(
        $form_state->getValue('pass', ''),
        $user,
        $user->getRoles()
    );
    // Adds the password status table to the reset pass form.
    $form['password_policy_status'] = [
      '#type' => 'item',
      '#theme' => 'password_policy_status',
      '#prefix' => '<div id="password-policy-status">',
      '#suffix' => '</div>',
      '#constraints' => $constraints,
      '#weight' => -1,
      '#states' => [
        'invisible' => [
          ':input[name="pass[pass1]"]' => ['value' => ''],
        ],
      ],
    ];
  }
}

/**
 * Implements hook_element_info_alter().
 */
function prlp_password_policy_element_info_alter(array &$types) {
  if (isset($types['password_confirm'])) {
    if (\Drupal::service('module_handler')->moduleExists('password_policy')) {
      // Disable default processor from password_policy which requires a user
      // entity in form_state that we might not have in all cases (prlp).
      if (($key = array_search(
      'password_policy_check_constraints_password_confirm_process',
      $types['password_confirm']['#process'])) !== FALSE) {
        unset($types['password_confirm']['#process'][$key]);
      }
    }
    if (\Drupal::service('module_handler')->moduleExists('password_policy_extras')) {
      // Disable processor from password_policy_extras module, if present.
      if (($key = array_search(
      'password_policy_extras_check_constraints_password_confirm_process',
      $types['password_confirm']['#process'])) !== FALSE) {
        unset($types['password_confirm']['#process'][$key]);
      }
    }
    $types['password_confirm']['#process'][] = 'prlp_password_policy_check_constraints_password_confirm_process';
  }
}

/**
 * Process callback to add Ajax validation to password_confirm element.
 */
function prlp_password_policy_check_constraints_password_confirm_process($element, FormStateInterface $form_state, array $form) {
  if (\Drupal::service('prlp_password_policy.validation_manager')->tableShouldBeVisible()) {
    // We enable Ajax in all cases for now even if a user object is not present.
    $element['pass1']['#ajax'] = [
      'event' => 'change',
      'callback' => '_prlp_password_policy_check_constraints',
      'method' => 'replaceWith',
      'wrapper' => 'password-policy-status',
      'disable-refocus' => FALSE,
    ];
  }
  return $element;
}

/**
 * Ajax callback to update password policy constraints table.
 */
function _prlp_password_policy_check_constraints(array $form, FormStateInterface $form_state) {
  if (isset($form['account']['password_policy_status'])) {
    return $form['account']['password_policy_status'];
  }
  // In some cases the password status is not in the account fieldset (prlp).
  elseif (isset($form['password_policy_status'])) {
    return $form['password_policy_status'];
  }
}
