<?php

/**
 * @file
 * Hook implementations for the term_condition module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function term_condition_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.term_condition':
      $filepath = dirname(__FILE__) . '/README.md';

      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
        return '<pre>' . $readme . '</pre>';
      }
  }
}
