# Required environmental variables should be set via the CircleCI web interface:
#
# - ACQUIA_USER
#     Cloud API E-mail
# - ACQUIA_TOKEN
#     Cloud API Private key. Located in your profile under security.
#     See: https://docs.acquia.com/acquia-cloud/api/auth
# - ACQUIA_CANONICAL_ENV
#     Environment to get database from. Usually "prod".
# - ACQUIA_ENDPOINT
#     Cloud API Endpoint. Usually "https://cloudapi.acquia.com/v1".
# - ACQUIA_REALM
#     Cloud API Realm. Usually "prod" or "devcloud".
#     See: https://docs.acquia.com/acquia-cloud/api#realm
# - ACQUIA_SITE
#     Cloud API Site parameter.
# - ACQUIA_REPO
#     Acquia git repo url.
# - ACQUIA_BOT_EMAIL
#     Email used to commit deployment commits.
# - ACQUIA_BOT_NAME
#     Display name use for the deployment committer.

version: 2
defaults: &defaults
  docker:
    - image: circleci/php:7.3-node-browsers
      environment:
        DATE_TIMEZONE: America/Chicago
        TERM: xterm
        ACQUIA_BOT_EMAIL: generalredneck+deploybot@gmail.com
        ACQUIA_BOT_NAME: "Deploying Redneck"
  working_directory: ~/project

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: sudo composer self-update
      - run: sudo apt-get update
      - run: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      - run: sudo docker-php-ext-install -j$(nproc) iconv
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run: sudo docker-php-ext-install gd mbstring opcache pdo pdo_mysql zip
      - run: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - run: composer install
      - run: echo "build assets for deploying" && composer build-assets
      - run: echo "deploying to the $circle_branch on acquia."
      - run: git config --global user.email "$ACQUIA_BOT_EMAIL"
      - run: git config --global user.name "$ACQUIA_BOT_NAME"
      - run: "sed -i '1,/######## ACQUIA IGNORE BELOW THIS LINE ########/d' .gitignore"
      # remove any .git directories that may exist in vendor libraries* so those
      # libraries don't get excluded from our repo. Remember kiddies somedir/*
      # returns all files/dirs that are NOT dot (hidden). This protects our repos'
      # .git folder from being blown away.
      - run: find ./* -type d | grep .git | xargs rm -rf
      # Remove unwanted gitignores here. Follow the example below.
      # Remove simplesamlphp .gitignore which would cause our config and metadata
      # symlinks to be ignored. If it's already not there, GREAT!
      # - rm ./vendor/simplesamlphp/simplesamlphp/.gitignore || exit 0
      # Commit and push to Acquia.
      - run: git add .
      - run: git commit -am "Built assets."
      - run: git push origin $CIRCLE_BRANCH:$CIRCLE_BRANCH-deploy -f --tags
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
                - /release-.*/

