commerce_recurring.commerce_prorater.plugin.stepped_proportional:
  type: mapping
  mapping:
    steps:
      type: integer
      label: Steps
    step_interval:
      type: mapping
      label: 'Step interval'
      mapping:
        period:
          type: string
          label: Period
        interval:
          type: integer
          label: Interval

commerce_recurring.commerce_billing_schedule.plugin.fixed_with_free_rollover:
  type: mapping
  mapping:
    interval:
      type: mapping
      label: 'Interval'
      mapping:
        number:
          type: integer
          label: Number
        unit:
          type: string
          label: Unit
    start_month:
      type: integer
      label: 'Start month'
    start_day:
      type: integer
      label: 'Start day'
    rollover_interval:
      type: mapping
      label: 'Rollover interval'
      mapping:
        period:
          type: string
          label: Period
        interval:
          type: integer
          label: Interval
