<?php

/**
 * Implements hook_preprocess_commerce_subscription().
 */
function commerce_recurring_log_preprocess_commerce_subscription(&$variables) {
  /** @var \Drupal\commerce_recurring\Entity\SubscriptionInterface $subscription */
  $subscription = $variables['elements']['#commerce_subscription'];
  // Adds the view inside the recurring orders section to view it in the primary entity section.
  $variables['subscription']['orders'][] = [
    '#type' => 'fieldset',
    'activity' => [
      '#type' => 'view',
      '#name' => 'commerce_activity',
      '#display_id' => 'default',
      '#arguments' => [$subscription->id(), 'commerce_subscription'],
      '#embed' => TRUE,
    ],
    '#title' => t('Subscription activity'),
  ];
}
