commerce_checkout_link.settings:
  type: config_object
  label: 'Commerce checkout link settings'
  mapping:
    use_changed_timestamp:
      type: integer
      label: 'Require hash to match with order using changed timestamp'
