<?php

/**
 * @file
 * Contains mcgreen_acres_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mcgreen_acres_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mcgreen_acres_custom module.
    case 'help.page.mcgreen_acres_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom functionality for McGreen Acres site.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mcgreen_acres_custom_theme() {
  return [
    'mcgreen_acres_custom' => [
      'render element' => 'children',
    ],
    'search_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
